kind: PersistentVolume
apiVersion: v1
metadata:
  name: data
  namespace: efk
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/C/tmp/data"