apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  labels:
    app: curator
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: curator
          restartPolicy: OnFailure
          containers:
            - name: curator
              image: dev.docker.repo.dev.icw.int/icw/curator:1.0-SNAPSHOT
              imagePullPolicy: Always
              args:
                - curator
                - --config
                - /tmp/config.yaml
                - /tmp/actions.yaml
              ports:
                - containerPort: 80
              env:
                - name: INDEX_DELETION_AGE_IN_DAYS
                  value: "1"
              volumeMounts:
                - name: curator-configmap
                  mountPath: /tmp/
          volumes:
            - name: curator-configmap
              configMap:
                name: curator-configmap
---
apiVersion: v1
data:
  actions.yaml: |
    actions:
      1:
        action: delete_indices
        description: "Delete indices older than x days"
        options:
          continue_if_exception: False
        filters:
          - filtertype: age
            source: name
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: ${INDEX_DELETION_AGE_IN_DAYS}
          - filtertype: kibana
            exclude: True
  config.yaml: |
    client:
      hosts: [ "es-cluster-0.elasticsearch", "es-cluster-1.elasticsearch", "es-cluster-2.elasticsearch"]
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False

    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
kind: ConfigMap
metadata:
  name: curator-configmap
  namespace: icw-ehealth-suite-system
